<?php

$rows = $this->getCollection();

?>
	<?php require_once 'View/html/header.phtml';?>
	<div class="title9">
		<div class="main9">
			<?php echo $this->getTitle();?>
		</div>
		<div class="main99">
			<?php foreach ($this->getButtons() as $key => $button): ?>
			<a type="button" class="btn btn-secondary" href="<?php echo $button['url'];?>"><?php echo $button['title']?></a>
			<?php endforeach;?>
		</div>
	</div>
	<table class="table">
		<tr>
			<?php foreach ($this->getColumns() as $key => $column): ?>
			<td><?php echo $column['title'];?></td>
			<?php endforeach;?>
			<?php foreach ($this->getActions() as $key => $action): ?>
			<td><?php echo $action['title'];?></td>
			<?php endforeach;?>
		</tr>
		<?php if (!$rows):?>
		<tr>
			<td>No records available.</td>
		</tr>
		<?php else:?>
		 <?php foreach ($rows as $row): ?>
		 	<tr>
			<?php foreach ($this->getColumns() as $key => $column): ?>
		 		<td> <?php echo $this->getColumnValue($row,$key); ?></td>
			<?php endforeach;?>
			<?php foreach ($this->getActions() as $key => $action): ?>
		 		<td><a href="<?php $method = $action['method']; echo $this->$method($row,$key);?>"><?php echo $action['title']?></td>
			<?php endforeach;?>
		 		</tr>
			
		<?php endforeach ?>
		<?php endif;?>
		<nav aria-label="Page navigation example">
	<ul class="pagination">
		<li class="page-item"><a class="page-link" href="<?php echo $this->getUrl('grid',null,['p' => $this->getPager()->start]) ?>">Start</a></li>
		<li class="page-item"><a class="page-link" href="<?php echo $this->getUrl('grid',null,['p' => $this->getPager()->previous]) ?>">Previous</a></li>
		<li class="page-item"><a class="page-link" href="<?php echo $this->getUrl('grid',null,['p' => $this->getPager()->currentPage]) ?>">Current</a></li>
		<li class="page-item"><a class="page-link" href="<?php echo $this->getUrl('grid',null,['p' => $this->getPager()->next]) ?>">Next</a></li>
		<li class="page-item"><a class="page-link" href="<?php echo $this->getUrl('grid',null,['p' => $this->getPager()->end]) ?>">end</a></li>
	</ul>
</nav>
	</table>
